---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmware-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: tanzu-gold-storage-policy
  volumeMode: Filesystem
