---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm-selector: vmware-vm
  name: vmware-vm
spec:
  imageName: vmi-6ab7ee61fca569000
  className: best-effort-xsmall
  powerState: poweredOn
  storageClass: tanzu-gold-storage-policy
  advancedOptions:
    defaultVolumeProvisioningOptions:
      thinProvisioned: true
  volumes:
  - name: vmware-vol
    persistentVolumeClaim:
      claimName: vmware-pvc
  networkInterfaces:
  - networkType: vsphere-distributed
    networkName: dvpg-workload-network
  readinessProbe:
    tcpSocket:
      port: 22
  vmMetadata:
    secretName: vmware-configmap
    transport: CloudInit
